package com.lean.tech.constans;

public interface ConstantsSql {
	
	String FIND_EMPLOYEE_BY_POSITION = "SELECT PO.ID AS IDPOSITION, PO.NAME AS NAMEPOSITION, E.ID AS IDEMPLOYEE, E.SALARY, P.NAME, P.LAST_NAME AS LASTNAME, P.ADDRESS, P.CELLPHONE, P.CITY_NAME AS CITYNAME \r\n"
			+ "FROM EMPLOYEE E \r\n" + "INNER JOIN PERSON P ON E.id_person=p.id\r\n"
			+ "INNER JOIN POSITION PO ON E.id_position=po.id\r\n" + "ORDER BY SALARY DESC;\r\n";
	
	String FIND_BY_NAME_OR_POSITION = "SELECT PE.ID, PE.NAME, PE.LAST_NAME as LASTNAME, PE.ADDRESS, PE.CELLPHONE, PE.CITY_NAME AS CITYNAME\r\n"
			+ "FROM PERSON PE \r\n" + "WHERE PE.ID IN (SELECT P.ID\r\n" + "FROM PERSON P WHERE P.NAME = :name)\r\n"
			+ "OR\r\n" + "PE.ID IN (SELECT E.ID_PERSON \r\n"
			+ "FROM EMPLOYEE E WHERE ID_POSITION IN ( SELECT PO.ID FROM POSITION PO WHERE PO.NAME = :position) )";


}
